repos:
    - repo: https://github.com/google/yamlfmt
      rev: v0.20.0 # Should match your locally installed version
      hooks:
        - id: yamlfmt
          description: This hook uses github.com/google/yamlfmt to format yaml files.
          language: system # Relies on yamlfmt to be installed on my system. See docs/yamlfmt.md
          types: [yaml]
          #pass_filenames: true # Only checks staged files by default
