---
# Test inventory - Default
l1:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.61
    groups:
        - leaf_group
l2:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.62
    groups:
        - leaf_group
l3:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.63
    groups:
        - leaf_group
l4:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.64
    groups:
        - leaf_group
l5:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.65
    groups:
        - leaf_group
s1:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.121
    groups:
        - spine_group
s2:
    username: admin
    password: admin
    platform: arista_ceos
    hostname: 172.100.100.122
    groups:
        - spine_group
h1:
    username:
    password:
    platform: linux
    hostname: 172.100.100.21
    groups:
        - host_group
h2:
    username:
    password:
    platform: linux
    hostname: 172.100.100.22
    groups:
        - host_group
h3:
    username:
    password:
    platform: linux
    hostname: 172.100.100.23
    groups:
        - host_group
h4:
    username:
    password:
    platform: linux
    hostname: 172.100.100.24
    groups:
        - host_group
h5:
    username:
    password:
    platform: linux
    hostname: 172.100.100.25
    groups:
        - host_group
